//! `linear schema` output, pinned against golden files captured from the
//! **pre-refactor** binary.
//!
//! The goldens in `tests/fixtures/` were produced by running the old build
//! (`/opt/data/bin/linear`, i.e. the binary from before this refactor) against a
//! local mock serving `tests/fixtures/schema_fixture.json`, so nothing here is
//! circular: the expected bytes were never generated by the code under test.
//! They exist because the refactor replaced the generic `serde_json::Value`
//! tree with borrowed typed structs, and `--json` has to re-serialise that model
//! byte for byte.
//!
//! `schema_fixture.json` is the `data` object of an `IntrospectionQuery`
//! response and covers an object, interface, union, enum, input object and
//! scalar type; a deprecated field and a deprecated enum value; arguments with
//! and without descriptions (inline vs multi-line argument blocks); block-string
//! and escaped-string descriptions; a specified scalar, a `__`-prefixed type
//! and two specified directives that must be omitted from the SDL; natural-order
//! sorting of types, fields, args, enum values, interfaces, union members and
//! directive locations; and a non-conventional mutation root name, which forces
//! an explicit `schema { ... }` block.

mod common;

use common::{mock_env, run_cli, MockLinearServer, MockResponse};
use serde_json::{json, Value};

const FIXTURE: &str = include_str!("fixtures/schema_fixture.json");
const GOLDEN_SDL: &str = include_str!("fixtures/schema.sdl");
const GOLDEN_JSON: &str = include_str!("fixtures/schema.json");

/// A mock Linear API answering the introspection query with the fixture.
fn introspection_server() -> MockLinearServer {
    let data: Value = serde_json::from_str(FIXTURE).expect("fixture is valid JSON");
    MockLinearServer::start(vec![MockResponse::new(
        "IntrospectionQuery",
        json!({ "data": data }),
    )])
}

fn assert_succeeded(output: &common::CliOutput) {
    assert!(
        output.success(),
        "expected exit 0, got {:?}\nstderr: {}",
        output.code,
        output.stderr
    );
}

#[test]
fn schema_sdl_matches_the_pre_refactor_golden() {
    let server = introspection_server();
    let output = run_cli(&["schema"], &mock_env(&server));
    assert_succeeded(&output);
    assert_eq!(output.stdout, GOLDEN_SDL);
}

#[test]
fn schema_json_matches_the_pre_refactor_golden() {
    let server = introspection_server();
    let output = run_cli(&["schema", "--json"], &mock_env(&server));
    assert_succeeded(&output);
    assert_eq!(output.stdout, GOLDEN_JSON);
}

/// The `-o` path must write the same bytes as stdout, including exactly one
/// trailing newline.
#[test]
fn schema_written_to_a_file_matches_the_golden() {
    let server = introspection_server();
    let dir = tempfile::tempdir().expect("temp dir");
    let path = dir.path().join("schema.sdl");
    let path = path.to_str().expect("utf-8 path");

    let output = run_cli(&["schema", "-o", path], &mock_env(&server));
    assert_succeeded(&output);
    assert_eq!(output.stdout, format!("Schema written to {path}\n"));

    let written = std::fs::read_to_string(path).expect("read schema file");
    assert_eq!(written, GOLDEN_SDL);
    assert!(
        written.ends_with('\n') && !written.ends_with("\n\n"),
        "the file ends with exactly one newline"
    );
}

#[test]
fn schema_json_written_to_a_file_matches_the_golden() {
    let server = introspection_server();
    let dir = tempfile::tempdir().expect("temp dir");
    let path = dir.path().join("schema.json");
    let path = path.to_str().expect("utf-8 path");

    let output = run_cli(&["schema", "--json", "-o", path], &mock_env(&server));
    assert_succeeded(&output);

    let written = std::fs::read_to_string(path).expect("read schema file");
    assert_eq!(written, GOLDEN_JSON);
    assert!(
        written.ends_with('\n') && !written.ends_with("\n\n"),
        "the file ends with exactly one newline"
    );
}
